### Zoom no Rosto, convertendo para escala de cinza, concatenando matrizes 3D -> 2D

In [111]:
import cv2
import numpy as np
import os
import matplotlib.pyplot as plt
from PIL import Image
from skimage import color
from skimage import io

import seaborn as sns
import pandas as pd
import math as math
from scipy import stats

In [102]:
img_folder_path = 'img/'
imgPaths = [img_folder_path+name for name in os.listdir(img_folder_path) if not name[0] == '.']

#print(imgPaths)

In [104]:
faces = []
zoom = []
matrix= []

size = 100,100
contador=0

for imagem in (imgPaths):
    
    img = cv2.imread(imagem)
        
    face_cascade = cv2.CascadeClassifier("utils/haarcascade_frontalface_default.xml")
    eye_cascade = cv2.CascadeClassifier('utils/haarcascade_eye.xml')
    
    #plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    #plt.show()
    
    img1 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
    
    detected_faces = face_cascade.detectMultiScale(gray) 
    
    for(x, y, w, h) in detected_faces:
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img1[y:y+h, x:x+w]
        
        eyes = eye_cascade.detectMultiScale(roi_gray)
        
        if len(eyes) > 1:
            
            faces.append(np.array(roi_color))
            
            ultima= faces[len(faces)-1]
            gray = cv2.cvtColor(ultima, cv2.COLOR_RGB2GRAY) 
            foto = Image.fromarray(gray)
            foto.thumbnail(size)
            matriz=np.array(foto)
            zoom.append(matriz)
            
            a = zoom[len(zoom)-1]
            b= np.concatenate(a)
            
            if len(b)==10000:
                foto.save('rostos\{}.png'.format(contador)) 

                fotooriginal = Image.fromarray(img1)
                fotooriginal.save('img_utilizaveis\{}.png'.format(contador))
                contador+=1
                matrix.append(b)

#            cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
            
#            for (ex,ey,ew,eh) in eyes:
#                cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

### Clustering

In [109]:
kmeans = KMeans(n_clusters=5, random_state=0).fit(matrix)
kmeans.labels_

array([4, 0, 3, 3, 0, 4, 0, 1, 1, 4, 4, 1, 1, 3, 3, 1, 2, 2, 1, 2, 3, 4,
       1, 1, 0, 3, 4, 2, 2, 0, 3, 0, 4, 2, 4, 1, 1, 1, 1, 1, 2, 2, 4, 1,
       1, 2, 1, 1, 0, 4, 3, 0, 2, 3, 1, 0, 0, 0, 0, 0, 0, 4, 1, 2, 2, 2,
       3, 0, 3, 3, 2, 2, 1, 4, 3, 2, 1, 2, 4, 0, 1, 4, 1, 3, 2, 3, 2, 4,
       2, 2, 4, 4, 4, 4, 3, 1, 1, 4, 2, 0, 2, 4, 1, 3, 0, 0, 2, 0, 0, 4,
       0, 2, 1, 3, 2, 2, 0, 1, 4, 3, 3, 1, 2, 4, 4, 3, 4, 3, 3, 2, 0, 4,
       2, 4, 2, 3, 4, 2, 4, 3, 1, 1, 4, 3, 2, 2, 4, 2, 0, 4, 0, 2, 0, 0,
       1, 0, 4, 2, 4, 1, 4, 2, 1, 2, 2, 2, 1, 3, 0, 4, 0, 3, 2, 2, 2, 2,
       3, 4, 3, 4, 4, 2, 4, 2, 0, 0, 3, 1, 1, 3, 4, 4, 4, 0, 4, 2, 3, 1,
       0, 1, 1, 2, 2, 4, 3, 3, 4, 4, 0, 3, 4, 2, 1, 2, 1, 4, 1, 3, 3, 3,
       0, 4, 0, 4, 3, 1, 4, 1, 0, 3, 3, 0, 0, 4, 0, 0, 1, 2, 0, 1, 4, 1,
       0, 4, 1, 4, 4, 4, 1, 3, 4, 2, 2, 0, 3, 1, 2, 2, 1, 2, 2, 2, 2, 0,
       3, 2, 4, 2, 3, 3, 1, 4, 2, 2, 1, 2, 1, 4, 3, 3, 2, 1, 4, 1, 2, 0,
       2, 4, 0, 4, 2, 2, 2, 4, 4, 2, 1, 2, 0, 2, 2, 1, 0, 4, 0, 0, 4, 4,
       3, 4, 0, 2, 4, 2, 4, 3, 1, 3, 3, 4, 2, 3, 4, 2, 4, 2, 4, 4, 2, 0,
       2, 1, 2, 4, 4, 0, 0, 2, 2, 2, 3, 1, 4, 4, 4, 4, 3, 3, 2, 4, 3, 0,
       2, 1, 4, 4, 2, 1, 1, 4, 0, 1, 2, 4, 3, 2, 2, 2, 0, 4, 4, 0, 2, 1,
       4, 1, 1, 2, 3, 4, 4, 0, 1, 3, 2, 1, 2, 2, 4, 1, 3, 3, 1, 3, 0, 0,
       3, 4, 1, 4, 0, 2, 2, 0, 4, 4, 4, 2, 2, 4, 2, 2, 4, 3, 4, 3, 4, 2,
       1, 1, 4, 0, 3, 2, 2, 2, 3, 2, 1, 1, 0, 0, 2, 2, 4, 4, 3, 3, 0, 2,
       0, 1, 2, 1, 1, 3, 4, 3, 3, 4, 0, 2, 0, 2, 2, 2, 0, 3, 2, 1, 0, 2,
       0, 2, 2, 2, 0, 2, 4, 4, 2, 4, 1, 4, 0, 1, 2, 0, 1, 0, 1, 2, 0, 4,
       4, 0, 4, 3, 4, 2, 4, 3, 4, 1, 0, 4])

In [112]:
tabela = pd.read_excel('Classificação P3.xlsx') 
lista = kmeans.labels_.tolist()

tabela.insert(loc=0, column='Cluster', value=lista)
tabela = tabela.set_index('Fotos')

tabela

       Cluster  Like
Fotos
0.0          4   1.0
1.0          0   1.0
2.0          3   0.0
3.0          3   0.0
4.0          0   1.0
5.0          4   1.0
6.0          0   1.0
7.0          1   0.0
8.0          1   0.0
9.0          4   0.0
10.0         4   1.0
11.0         1   0.0
12.0         1   0.0
13.0         3   0.0
14.0         3   0.0
15.0         1   0.0
16.0         2   0.0
17.0         2   0.0
18.0         1   0.0
19.0         2   0.0
20.0         3   0.0
21.0         4   0.0
22.0         1   0.0
23.0         1   0.0
24.0         0   0.0
25.0         3   0.0
26.0         4   0.0
27.0         2   0.0
28.0         2   0.0
29.0         0   1.0
...        ...   ...
466.0        0   0.0
467.0        2   0.0
468.0        4   0.0
469.0        4   0.0
470.0        2   0.0
471.0        4   0.0
472.0        1   0.0
473.0        4   0.0
474.0        0   0.0
475.0        1   0.0
476.0        2   0.0
477.0        0   0.0
478.0        1   0.0
479.0        0   1.0
480.0        1   0.0
481.0        2   1.0
482.0        0   1.0
483.0        4   0.0
484.0        4   0.0
485.0        0   0.0
486.0        4   0.0
487.0        3   0.0
488.0        4   0.0
489.0        2   1.0
490.0        4   1.0
491.0        3   0.0
492.0        4   1.0
493.0        1   1.0
494.0        0   0.0
495.0        4   0.0

[496 rows x 2 columns]

In [122]:
tabela[(tabela.Like == 1) & (tabela.Cluster == 0)]

AttributeError: 'list' object has no attribute 'Like'

In [ ]:
#limpeza das imagens - deixar na pasta original somente as que o programa cortou direito
#fazer o clustering dessas imagens
#preencher tabela de treinamento e de teste
#usar algum método do scikit learn para preencher o teste previsto
#comparar teste (acuracia)
#se estiver ok (>70%), aí partimos para o programa em si
#aleatoriamente pegar uma(ou mais) fotos de cada cluster e apresentar para o usuario
#Automaticamente daremos like para as fotos do mesmo cluster que ele também deu like.
#Se possível, fazer uma interface apresentável